name: Test

on:
  pull_request:
    types: [synchronize]
    branches:
      - develop
      - main

jobs:
  test-worflow:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3.1.0

      - name: Hi there from GitHub Actions DEV
        if: github.event.pull_request.base.ref == 'develop'
        run: |
          echo "Hi from DEV"

      - name: Hi there from GitHub Actions MAIN
        if: github.event.pull_request.base.ref == 'main'
        run: |
          echo "Hi from PROD"
  